INSERT INTO questions (question_id, question, answer, genre, difficulty) VALUES
('Q100', 'What is the capital of France?', 'Paris', 'Trivia', 'easy'),
('Q101', 'How many sides does a triangle have?', '3', 'Trivia', 'easy'),
('Q102', 'What color do you get when you mix red and white?', 'Pink', 'Trivia', 'easy'),
('Q103', 'What is the largest mammal in the world?', 'Blue Whale', 'Trivia', 'easy'),
('Q104', 'How many days are there in a week?', '7', 'Trivia', 'easy'),
('Q105', 'What is the opposite of hot?', 'Cold', 'Trivia', 'easy'),
('Q106', 'What do bees make?', 'Honey', 'Trivia', 'easy'),
('Q107', 'What is 2 + 2?', '4', 'Trivia', 'easy'),
('Q108', 'What animal says "moo"?', 'Cow', 'Trivia', 'easy'),
('Q109', 'How many months are in a year?', '12', 'Trivia', 'easy'),
('Q110', 'What is the first letter of the alphabet?', 'A', 'Trivia', 'easy'),
('Q111', 'What do you use to write on a blackboard?', 'Chalk', 'Trivia', 'easy'),
('Q112', 'What is frozen water called?', 'Ice', 'Trivia', 'easy'),
('Q113', 'How many wheels does a bicycle have?', '2', 'Trivia', 'easy'),
('Q114', 'What is the color of the sun?', 'Yellow', 'Trivia', 'easy'),
('Q115', 'What do caterpillars turn into?', 'Butterflies', 'Trivia', 'easy'),
('Q116', 'What is 5 + 5?', '10', 'Trivia', 'easy'),
('Q117', 'What animal is known as "man''s best friend"?', 'Dog', 'Trivia', 'easy'),
('Q118', 'How many fingers do you have on one hand?', '5', 'Trivia', 'easy'),
('Q119', 'What is the biggest planet in our solar system?', 'Jupiter', 'Trivia', 'easy'),
('Q120', 'What do you call a baby cat?', 'Kitten', 'Trivia', 'easy'),
('Q121', 'What is the capital of the United States?', 'Washington D.C.', 'Trivia', 'easy'),
('Q122', 'How many legs does a spider have?', '8', 'Trivia', 'easy'),
('Q123', 'What is the fastest land animal?', 'Cheetah', 'Trivia', 'easy'),
('Q124', 'What do you call a group of fish?', 'School', 'Trivia', 'easy'),
('Q125', 'What is 10 - 5?', '5', 'Trivia', 'easy'),
('Q126', 'What is the tallest mountain in the world?', 'Mount Everest', 'Trivia', 'easy'),
('Q127', 'What do you call a baby dog?', 'Puppy', 'Trivia', 'easy'),
('Q128', 'How many continents are there?', '7', 'Trivia', 'easy'),
('Q129', 'What is the smallest planet in our solar system?', 'Mercury', 'Trivia', 'easy'),
('Q130', 'What do you call water that falls from the sky?', 'Rain', 'Trivia', 'easy'),
('Q131', 'How many minutes are in an hour?', '60', 'Trivia', 'easy'),
('Q132', 'What is the primary color that is not red or blue?', 'Yellow', 'Trivia', 'easy'),
('Q133', 'What is the largest ocean?', 'Pacific Ocean', 'Trivia', 'easy'),
('Q134', 'What do you call a house made of ice?', 'Igloo', 'Trivia', 'easy'),
('Q135', 'How many eyes do most people have?', '2', 'Trivia', 'easy'),
('Q136', 'What is the capital of Italy?', 'Rome', 'Trivia', 'easy'),
('Q137', 'What do pandas eat?', 'Bamboo', 'Trivia', 'easy'),
('Q138', 'What is 3 x 3?', '9', 'Trivia', 'easy'),
('Q139', 'What do you call the person who delivers mail?', 'Mailman', 'Trivia', 'easy'),
('Q140', 'What is the chemical symbol for gold?', 'Au', 'Trivia', 'medium'),
('Q141', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Trivia', 'medium'),
('Q142', 'What is the smallest country in the world?', 'Vatican City', 'Trivia', 'medium'),
('Q143', 'Which planet is known as the Red Planet?', 'Mars', 'Trivia', 'medium'),
('Q144', 'What is the longest river in the world?', 'Nile River', 'Trivia', 'medium'),
('Q145', 'Who wrote Romeo and Juliet?', 'William Shakespeare', 'Trivia', 'medium'),
('Q146', 'What is the hardest natural substance on Earth?', 'Diamond', 'Trivia', 'medium'),
('Q147', 'How many bones are in the human body?', '206', 'Trivia', 'medium'),
('Q148', 'What is the capital of Australia?', 'Canberra', 'Trivia', 'medium'),
('Q149', 'Which gas makes up most of the Earth''s atmosphere?', 'Nitrogen', 'Trivia', 'medium'),
('Q150', 'What is the speed of light?', '299,792,458 meters per second', 'Trivia', 'medium'),
('Q151', 'Who discovered penicillin?', 'Alexander Fleming', 'Trivia', 'medium'),
('Q152', 'What is the largest desert in the world?', 'Antarctica', 'Trivia', 'medium'),
('Q153', 'How many chambers does a human heart have?', '4', 'Trivia', 'medium'),
('Q154', 'What is the currency of Japan?', 'Yen', 'Trivia', 'medium'),
('Q155', 'Which element has the chemical symbol O?', 'Oxygen', 'Trivia', 'medium'),
('Q156', 'What is the deepest ocean trench?', 'Mariana Trench', 'Trivia', 'medium'),
('Q157', 'Who invented the telephone?', 'Alexander Graham Bell', 'Trivia', 'medium'),
('Q158', 'What is the largest organ in the human body?', 'Skin', 'Trivia', 'medium'),
('Q159', 'Which country has the most natural lakes?', 'Canada', 'Trivia', 'medium'),
('Q160', 'What is the formula for water?', 'H2O', 'Trivia', 'medium'),
('Q161', 'Who was the first person to walk on the moon?', 'Neil Armstrong', 'Trivia', 'medium'),
('Q162', 'What is the capital of Brazil?', 'Brasília', 'Trivia', 'medium'),
('Q163', 'Which blood type is known as the universal donor?', 'O negative', 'Trivia', 'medium'),
('Q164', 'What is the most abundant element in the universe?', 'Hydrogen', 'Trivia', 'medium'),
('Q165', 'Who composed The Four Seasons?', 'Antonio Vivaldi', 'Trivia', 'medium'),
('Q166', 'What is the largest island in the world?', 'Greenland', 'Trivia', 'medium'),
('Q167', 'How many strings does a standard guitar have?', '6', 'Trivia', 'medium'),
('Q168', 'What is the study of earthquakes called?', 'Seismology', 'Trivia', 'medium'),
('Q169', 'Which vitamin is produced when skin is exposed to sunlight?', 'Vitamin D', 'Trivia', 'medium'),
('Q170', 'What is the smallest bone in the human body?', 'Stapes', 'Trivia', 'hard'),
('Q171', 'Who wrote "One Hundred Years of Solitude"?', 'Gabriel García Márquez', 'Trivia', 'hard'),
('Q172', 'What is the rarest blood type?', 'Rh-null', 'Trivia', 'hard'),
('Q173', 'Which element has the highest melting point?', 'Tungsten', 'Trivia', 'hard'),
('Q174', 'What is the capital of Bhutan?', 'Thimphu', 'Trivia', 'hard'),
('Q175', 'Who discovered the structure of DNA?', 'Watson, Crick, Franklin, and Wilkins', 'Trivia', 'hard'),
('Q176', 'What is the term for a word that reads the same backwards and forwards?', 'Palindrome', 'Trivia', 'hard'),
('Q177', 'Which mathematician is known for his incompleteness theorems?', 'Kurt Gödel', 'Trivia', 'hard'),
('Q178', 'What is the most electronegative element?', 'Fluorine', 'Trivia', 'hard'),
('Q179', 'Who painted "The Persistence of Memory"?', 'Salvador Dalí', 'Trivia', 'hard'),
('Q180', 'What is the largest moon of Saturn?', 'Titan', 'Trivia', 'hard'),
('Q181', 'Which philosopher wrote "Being and Time"?', 'Martin Heidegger', 'Trivia', 'hard'),
('Q182', 'What is the half-life of Carbon-14?', '5,730 years', 'Trivia', 'hard'),
('Q183', 'Who composed the opera "The Ring of the Nibelung"?', 'Richard Wagner', 'Trivia', 'hard'),
('Q184', 'What is the name of the theoretical boundary around a black hole?', 'Event Horizon', 'Trivia', 'hard'),
('Q185', 'Which enzyme is responsible for unwinding DNA?', 'Helicase', 'Trivia', 'hard'),
('Q186', 'What is the capital of Kyrgyzstan?', 'Bishkek', 'Trivia', 'hard'),
('Q187', 'Who proved Fermat''s Last Theorem?', 'Andrew Wiles', 'Trivia', 'hard'),
('Q188', 'What is the strongest intermolecular force?', 'Hydrogen bonding', 'Trivia', 'hard'),
('Q189', 'Which author wrote "Gravity''s Rainbow"?', 'Thomas Pynchon', 'Trivia', 'hard'),
('Q190', 'What is the name of the hypothetical particle that gives mass to other particles?', 'Higgs boson', 'Trivia', 'hard'),
('Q191', 'Who developed the theory of continental drift?', 'Alfred Wegener', 'Trivia', 'hard'),
('Q192', 'What is the most common isotope of uranium?', 'Uranium-238', 'Trivia', 'hard'),
('Q193', 'Which composer wrote "The Well-Tempered Clavier"?', 'Johann Sebastian Bach', 'Trivia', 'hard'),
('Q194', 'What is the name of the effect where time dilates due to gravity?', 'Gravitational time dilation', 'Trivia', 'hard'),
('Q195', 'Who discovered the neutron?', 'James Chadwick', 'Trivia', 'hard'),
('Q196', 'What is the term for the study of the origin and evolution of the universe?', 'Cosmology', 'Trivia', 'hard'),
('Q197', 'Which programming language was developed by Guido van Rossum?', 'Python', 'Trivia', 'hard'),
('Q198', 'What is the name of the process by which plants convert light energy into chemical energy?', 'Photosynthesis', 'Trivia', 'hard'),
('Q199', 'Who formulated the three laws of planetary motion?', 'Johannes Kepler', 'Trivia', 'hard');
