INSERT INTO questions (question_id, question, answer, genre, difficulty, question_options) VALUES
('Q001', 'What is the capital of France?', 'Paris', 'Trivia', 'easy', '["London", "Berlin", "Madrid"]'),
('Q002', 'How many sides does a triangle have?', '3', 'Trivia', 'easy', '["4", "5", "6"]'),
('Q003', 'What color do you get when you mix red and white?', 'Pink', 'Trivia', 'easy', '["Purple", "Orange", "Yellow"]'),
('Q004', 'What is the largest mammal in the world?', 'Blue Whale', 'Trivia', 'easy', '["Elephant", "Giraffe", "Hippopotamus"]'),
('Q005', 'How many days are there in a week?', '7', 'Trivia', 'easy', '["5", "6", "8"]'),
('Q006', 'What is the opposite of hot?', 'Cold', 'Trivia', 'easy', '["Warm", "Cool", "Freezing"]'),
('Q007', 'What do bees make?', 'Honey', 'Trivia', 'easy', '["Milk", "Butter", "Sugar"]'),
('Q008', 'What is 2 + 2?', '4', 'Trivia', 'easy', '["3", "5", "6"]'),
('Q009', 'What animal says "moo"?', 'Cow', 'Trivia', 'easy', '["Pig", "Sheep", "Horse"]'),
('Q010', 'How many months are in a year?', '12', 'Trivia', 'easy', '["10", "11", "13"]'),
('Q011', 'What is the first letter of the alphabet?', 'A', 'Trivia', 'easy', '["B", "C", "Z"]'),
('Q012', 'What do you use to write on a blackboard?', 'Chalk', 'Trivia', 'easy', '["Pen", "Pencil", "Marker"]'),
('Q013', 'What is frozen water called?', 'Ice', 'Trivia', 'easy', '["Snow", "Frost", "Hail"]'),
('Q014', 'How many wheels does a bicycle have?', '2', 'Trivia', 'easy', '["1", "3", "4"]'),
('Q015', 'What is the color of the sun?', 'Yellow', 'Trivia', 'easy', '["Orange", "Red", "White"]'),
('Q016', 'What do caterpillars turn into?', 'Butterflies', 'Trivia', 'easy', '["Moths", "Beetles", "Flies"]'),
('Q017', 'What is 5 + 5?', '10', 'Trivia', 'easy', '["9", "11", "15"]'),
('Q018', 'What animal is known as "man''s best friend"?', 'Dog', 'Trivia', 'easy', '["Cat", "Horse", "Bird"]'),
('Q019', 'How many fingers do you have on one hand?', '5', 'Trivia', 'easy', '["4", "6", "10"]'),
('Q020', 'What is the biggest planet in our solar system?', 'Jupiter', 'Trivia', 'easy', '["Saturn", "Earth", "Mars"]'),
('Q021', 'What do you call a baby cat?', 'Kitten', 'Trivia', 'easy', '["Puppy", "Cub", "Chick"]'),
('Q022', 'What is the capital of the United States?', 'Washington D.C.', 'Trivia', 'easy', '["New York", "Los Angeles", "Chicago"]'),
('Q023', 'How many legs does a spider have?', '8', 'Trivia', 'easy', '["6", "10", "12"]'),
('Q024', 'What is the fastest land animal?', 'Cheetah', 'Trivia', 'easy', '["Lion", "Horse", "Leopard"]'),
('Q025', 'What do you call a group of fish?', 'School', 'Trivia', 'easy', '["Flock", "Herd", "Pack"]'),
('Q026', 'What is 10 - 5?', '5', 'Trivia', 'easy', '["3", "4", "6"]'),
('Q027', 'What is the tallest mountain in the world?', 'Mount Everest', 'Trivia', 'easy', '["K2", "Mount Kilimanjaro", "Mount McKinley"]'),
('Q028', 'What do you call a baby dog?', 'Puppy', 'Trivia', 'easy', '["Kitten", "Calf", "Foal"]'),
('Q029', 'How many continents are there?', '7', 'Trivia', 'easy', '["5", "6", "8"]'),
('Q030', 'What is the smallest planet in our solar system?', 'Mercury', 'Trivia', 'easy', '["Venus", "Mars", "Pluto"]'),
('Q031', 'What do you call water that falls from the sky?', 'Rain', 'Trivia', 'easy', '["Snow", "Hail", "Sleet"]'),
('Q032', 'How many minutes are in an hour?', '60', 'Trivia', 'easy', '["50", "70", "100"]'),
('Q033', 'What is the primary color that is not red or blue?', 'Yellow', 'Trivia', 'easy', '["Green", "Orange", "Purple"]'),
('Q034', 'What is the largest ocean?', 'Pacific Ocean', 'Trivia', 'easy', '["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"]'),
('Q035', 'What do you call a house made of ice?', 'Igloo', 'Trivia', 'easy', '["Cabin", "Hut", "Tent"]'),
('Q036', 'How many eyes do most people have?', '2', 'Trivia', 'easy', '["1", "3", "4"]'),
('Q037', 'What is the capital of Italy?', 'Rome', 'Trivia', 'easy', '["Milan", "Naples", "Florence"]'),
('Q038', 'What do pandas eat?', 'Bamboo', 'Trivia', 'easy', '["Fish", "Meat", "Fruit"]'),
('Q039', 'What is 3 x 3?', '9', 'Trivia', 'easy', '["6", "12", "15"]'),
('Q040', 'What do you call the person who delivers mail?', 'Mailman', 'Trivia', 'easy', '["Milkman", "Fireman", "Policeman"]'),
('Q041', 'What is the chemical symbol for gold?', 'Au', 'Trivia', 'medium', '["Ag", "Go", "Gd"]'),
('Q042', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Trivia', 'medium', '["Michelangelo", "Raphael", "Picasso"]'),
('Q043', 'What is the smallest country in the world?', 'Vatican City', 'Trivia', 'medium', '["Monaco", "San Marino", "Liechtenstein"]'),
('Q044', 'Which planet is known as the Red Planet?', 'Mars', 'Trivia', 'medium', '["Venus", "Jupiter", "Saturn"]'),
('Q045', 'What is the longest river in the world?', 'Nile River', 'Trivia', 'medium', '["Amazon River", "Mississippi River", "Yangtze River"]'),
('Q046', 'Who wrote Romeo and Juliet?', 'William Shakespeare', 'Trivia', 'medium', '["Charles Dickens", "Mark Twain", "Jane Austen"]'),
('Q047', 'What is the hardest natural substance on Earth?', 'Diamond', 'Trivia', 'medium', '["Steel", "Granite", "Quartz"]'),
('Q048', 'How many bones are in the human body?', '206', 'Trivia', 'medium', '["186", "226", "246"]'),
('Q049', 'What is the capital of Australia?', 'Canberra', 'Trivia', 'medium', '["Sydney", "Melbourne", "Perth"]'),
('Q050', 'Which gas makes up most of the Earth''s atmosphere?', 'Nitrogen', 'Trivia', 'medium', '["Oxygen", "Carbon Dioxide", "Argon"]'),
('Q051', 'What is the speed of light?', '299,792,458 meters per second', 'Trivia', 'medium', '["186,282 miles per second", "300,000 km/s", "299,792,458 km/s"]'),
('Q052', 'Who discovered penicillin?', 'Alexander Fleming', 'Trivia', 'medium', '["Louis Pasteur", "Marie Curie", "Jonas Salk"]'),
('Q053', 'What is the largest desert in the world?', 'Antarctica', 'Trivia', 'medium', '["Sahara", "Gobi", "Kalahari"]'),
('Q054', 'How many chambers does a human heart have?', '4', 'Trivia', 'medium', '["2", "3", "6"]'),
('Q055', 'What is the currency of Japan?', 'Yen', 'Trivia', 'medium', '["Won", "Yuan", "Ringgit"]'),
('Q056', 'Which element has the chemical symbol O?', 'Oxygen', 'Trivia', 'medium', '["Osmium", "Oganesson", "Olivine"]'),
('Q057', 'What is the deepest ocean trench?', 'Mariana Trench', 'Trivia', 'medium', '["Puerto Rico Trench", "Japan Trench", "Peru-Chile Trench"]'),
('Q058', 'Who invented the telephone?', 'Alexander Graham Bell', 'Trivia', 'medium', '["Thomas Edison", "Nikola Tesla", "Benjamin Franklin"]'),
('Q059', 'What is the largest organ in the human body?', 'Skin', 'Trivia', 'medium', '["Liver", "Lungs", "Brain"]'),
('Q060', 'Which country has the most natural lakes?', 'Canada', 'Trivia', 'medium', '["Finland", "Russia", "Sweden"]'),
('Q061', 'What is the formula for water?', 'H2O', 'Trivia', 'medium', '["H2O2", "HO2", "H3O"]'),
('Q062', 'Who was the first person to walk on the moon?', 'Neil Armstrong', 'Trivia', 'medium', '["Buzz Aldrin", "John Glenn", "Alan Shepard"]'),
('Q063', 'What is the capital of Brazil?', 'Brasília', 'Trivia', 'medium', '["Rio de Janeiro", "São Paulo", "Salvador"]'),
('Q064', 'Which blood type is known as the universal donor?', 'O negative', 'Trivia', 'medium', '["AB positive", "O positive", "A negative"]'),
('Q065', 'What is the most abundant element in the universe?', 'Hydrogen', 'Trivia', 'medium', '["Helium", "Oxygen", "Carbon"]'),
('Q066', 'Who composed The Four Seasons?', 'Antonio Vivaldi', 'Trivia', 'medium', '["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven"]'),
('Q067', 'What is the largest island in the world?', 'Greenland', 'Trivia', 'medium', '["Australia", "Madagascar", "Borneo"]'),
('Q068', 'How many strings does a standard guitar have?', '6', 'Trivia', 'medium', '["4", "8", "12"]'),
('Q069', 'What is the study of earthquakes called?', 'Seismology', 'Trivia', 'medium', '["Geology", "Meteorology", "Volcanology"]'),
('Q070', 'Which vitamin is produced when skin is exposed to sunlight?', 'Vitamin D', 'Trivia', 'medium', '["Vitamin C", "Vitamin A", "Vitamin K"]'),
('Q071', 'What is the smallest bone in the human body?', 'Stapes', 'Trivia', 'hard', '["Malleus", "Incus", "Hyoid"]'),
('Q072', 'Who wrote "One Hundred Years of Solitude"?', 'Gabriel García Márquez', 'Trivia', 'hard', '["Mario Vargas Llosa", "Jorge Luis Borges", "Octavio Paz"]'),
('Q073', 'What do you call a baby horse?', 'Foal', 'Trivia', 'easy', '["Colt", "Pony", "Calf"]'),
('Q074', 'How many hours are in a day?', '24', 'Trivia', 'easy', '["20", "25", "30"]'),
('Q075', 'What is the main ingredient in bread?', 'Flour', 'Trivia', 'easy', '["Sugar", "Salt", "Water"]'),
('Q076', 'What do you call frozen rain?', 'Hail', 'Trivia', 'easy', '["Snow", "Sleet", "Ice"]'),
('Q077', 'What is the opposite of up?', 'Down', 'Trivia', 'easy', '["Left", "Right", "Back"]'),
('Q078', 'How many legs does an insect have?', '6', 'Trivia', 'easy', '["4", "8", "10"]'),
('Q079', 'What is the color of grass?', 'Green', 'Trivia', 'easy', '["Blue", "Yellow", "Red"]'),
('Q080', 'What do you use to cut paper?', 'Scissors', 'Trivia', 'easy', '["Knife", "Ruler", "Pen"]'),
('Q081', 'What is the largest continent?', 'Asia', 'Trivia', 'medium', '["Africa", "North America", "Europe"]'),
('Q082', 'Who invented the light bulb?', 'Thomas Edison', 'Trivia', 'medium', '["Benjamin Franklin", "Nikola Tesla", "Alexander Bell"]'),
('Q083', 'What is the freezing point of water in Celsius?', '0', 'Trivia', 'medium', '["32", "-10", "100"]'),
('Q084', 'Which ocean is the smallest?', 'Arctic Ocean', 'Trivia', 'medium', '["Indian Ocean", "Atlantic Ocean", "Southern Ocean"]'),
('Q085', 'What is the capital of Canada?', 'Ottawa', 'Trivia', 'medium', '["Toronto", "Montreal", "Vancouver"]'),
('Q086', 'How many sides does a hexagon have?', '6', 'Trivia', 'medium', '["5", "7", "8"]'),
('Q087', 'What is the hardest rock?', 'Diamond', 'Trivia', 'medium', '["Granite", "Marble", "Quartz"]'),
('Q088', 'Which planet is closest to the sun?', 'Mercury', 'Trivia', 'medium', '["Venus", "Earth", "Mars"]'),
('Q089', 'What gas do plants absorb from the air?', 'Carbon Dioxide', 'Trivia', 'medium', '["Oxygen", "Nitrogen", "Hydrogen"]'),
('Q090', 'How many minutes are in half an hour?', '30', 'Trivia', 'easy', '["25", "35", "40"]'),
('Q091', 'What is the square root of 64?', '8', 'Trivia', 'medium', '["6", "7", "9"]'),
('Q092', 'Which element has the symbol Fe?', 'Iron', 'Trivia', 'hard', '["Gold", "Silver", "Lead"]'),
('Q093', 'What is the longest bone in the human body?', 'Femur', 'Trivia', 'hard', '["Tibia", "Humerus", "Radius"]'),
('Q094', 'Who painted "The Starry Night"?', 'Vincent van Gogh', 'Trivia', 'hard', '["Pablo Picasso", "Claude Monet", "Salvador Dalí"]'),
('Q095', 'What is the pH of pure water?', '7', 'Trivia', 'hard', '["0", "14", "10"]'),
('Q096', 'Which scientist developed the theory of relativity?', 'Albert Einstein', 'Trivia', 'hard', '["Isaac Newton", "Galileo Galilei", "Stephen Hawking"]'),
('Q097', 'What is the most spoken language in the world?', 'Mandarin Chinese', 'Trivia', 'medium', '["English", "Spanish", "Hindi"]'),
('Q098', 'How many chambers does a bird''s heart have?', '4', 'Trivia', 'hard', '["2", "3", "5"]'),
('Q099', 'What is the chemical formula for table salt?', 'NaCl', 'Trivia', 'hard', '["KCl", "CaCl2", "MgCl2"]'),
('Q100', 'Which country invented pizza?', 'Italy', 'Trivia', 'easy', '["Greece", "France", "Spain"]'),
('Q101', 'What is the capital of France?', 'Paris', 'Buzzer', 'easy', '["London", "Berlin", "Madrid"]'),
('Q102', 'How many sides does a triangle have?', '3', 'Buzzer', 'easy', '["4", "5", "6"]'),
('Q103', 'What color do you get when you mix red and white?', 'Pink', 'Buzzer', 'easy', '["Purple", "Orange", "Yellow"]'),
('Q104', 'What is the largest mammal in the world?', 'Blue Whale', 'Buzzer', 'easy', '["Elephant", "Giraffe", "Hippopotamus"]'),
('Q105', 'How many days are there in a week?', '7', 'Buzzer', 'easy', '["5", "6", "8"]'),
('Q106', 'What is the opposite of hot?', 'Cold', 'Buzzer', 'easy', '["Warm", "Cool", "Freezing"]'),
('Q107', 'What do bees make?', 'Honey', 'Buzzer', 'easy', '["Milk", "Butter", "Sugar"]'),
('Q108', 'What is 2 + 2?', '4', 'Buzzer', 'easy', '["3", "5", "6"]'),
('Q109', 'What animal says "moo"?', 'Cow', 'Buzzer', 'easy', '["Pig", "Sheep", "Horse"]'),
('Q110', 'How many months are in a year?', '12', 'Buzzer', 'easy', '["10", "11", "13"]'),
('Q111', 'What is the first letter of the alphabet?', 'A', 'Buzzer', 'easy', '["B", "C", "Z"]'),
('Q112', 'What do you use to write on a blackboard?', 'Chalk', 'Buzzer', 'easy', '["Pen", "Pencil", "Marker"]'),
('Q113', 'What is frozen water called?', 'Ice', 'Buzzer', 'easy', '["Snow", "Frost", "Hail"]'),
('Q114', 'How many wheels does a bicycle have?', '2', 'Buzzer', 'easy', '["1", "3", "4"]'),
('Q115', 'What is the color of the sun?', 'Yellow', 'Buzzer', 'easy', '["Orange", "Red", "White"]'),
('Q116', 'What do caterpillars turn into?', 'Butterflies', 'Buzzer', 'easy', '["Moths", "Beetles", "Flies"]'),
('Q117', 'What is 5 + 5?', '10', 'Buzzer', 'easy', '["9", "11", "15"]'),
('Q118', 'What animal is known as "man''s best friend"?', 'Dog', 'Buzzer', 'easy', '["Cat", "Horse", "Bird"]'),
('Q119', 'How many fingers do you have on one hand?', '5', 'Buzzer', 'easy', '["4", "6", "10"]'),
('Q120', 'What is the biggest planet in our solar system?', 'Jupiter', 'Buzzer', 'easy', '["Saturn", "Earth", "Mars"]'),
('Q121', 'What do you call a baby cat?', 'Kitten', 'Buzzer', 'easy', '["Puppy", "Cub", "Chick"]'),
('Q122', 'What is the capital of the United States?', 'Washington D.C.', 'Buzzer', 'easy', '["New York", "Los Angeles", "Chicago"]'),
('Q123', 'How many legs does a spider have?', '8', 'Buzzer', 'easy', '["6", "10", "12"]'),
('Q124', 'What is the fastest land animal?', 'Cheetah', 'Buzzer', 'easy', '["Lion", "Horse", "Leopard"]'),
('Q125', 'What do you call a group of fish?', 'School', 'Buzzer', 'easy', '["Flock", "Herd", "Pack"]'),
('Q126', 'What is 10 - 5?', '5', 'Buzzer', 'easy', '["3", "4", "6"]'),
('Q127', 'What is the tallest mountain in the world?', 'Mount Everest', 'Buzzer', 'easy', '["K2", "Mount Kilimanjaro", "Mount McKinley"]'),
('Q128', 'What do you call a baby dog?', 'Puppy', 'Buzzer', 'easy', '["Kitten", "Calf", "Foal"]'),
('Q129', 'How many continents are there?', '7', 'Buzzer', 'easy', '["5", "6", "8"]'),
('Q130', 'What is the smallest planet in our solar system?', 'Mercury', 'Buzzer', 'easy', '["Venus", "Mars", "Pluto"]'),
('Q131', 'What do you call water that falls from the sky?', 'Rain', 'Buzzer', 'easy', '["Snow", "Hail", "Sleet"]'),
('Q132', 'How many minutes are in an hour?', '60', 'Buzzer', 'easy', '["50", "70", "100"]'),
('Q133', 'What is the primary color that is not red or blue?', 'Yellow', 'Buzzer', 'easy', '["Green", "Orange", "Purple"]'),
('Q134', 'What is the largest ocean?', 'Pacific Ocean', 'Buzzer', 'easy', '["Atlantic Ocean", "Indian Ocean", "Arctic Ocean"]'),
('Q135', 'What do you call a house made of ice?', 'Igloo', 'Buzzer', 'easy', '["Cabin", "Hut", "Tent"]'),
('Q136', 'How many eyes do most people have?', '2', 'Buzzer', 'easy', '["1", "3", "4"]'),
('Q137', 'What is the capital of Italy?', 'Rome', 'Buzzer', 'easy', '["Milan", "Naples", "Florence"]'),
('Q138', 'What do pandas eat?', 'Bamboo', 'Buzzer', 'easy', '["Fish", "Meat", "Fruit"]'),
('Q139', 'What is 3 x 3?', '9', 'Buzzer', 'easy', '["6", "12", "15"]'),
('Q140', 'What do you call the person who delivers mail?', 'Mailman', 'Buzzer', 'easy', '["Milkman", "Fireman", "Policeman"]'),
('Q141', 'What is the chemical symbol for gold?', 'Au', 'Buzzer', 'medium', '["Ag", "Go", "Gd"]'),
('Q142', 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Buzzer', 'medium', '["Michelangelo", "Raphael", "Picasso"]'),
('Q143', 'What is the smallest country in the world?', 'Vatican City', 'Buzzer', 'medium', '["Monaco", "San Marino", "Liechtenstein"]'),
('Q144', 'Which planet is known as the Red Planet?', 'Mars', 'Buzzer', 'medium', '["Venus", "Jupiter", "Saturn"]'),
('Q145', 'What is the longest river in the world?', 'Nile River', 'Buzzer', 'medium', '["Amazon River", "Mississippi River", "Yangtze River"]'),
('Q146', 'Who wrote Romeo and Juliet?', 'William Shakespeare', 'Buzzer', 'medium', '["Charles Dickens", "Mark Twain", "Jane Austen"]'),
('Q147', 'What is the hardest natural substance on Earth?', 'Diamond', 'Buzzer', 'medium', '["Steel", "Granite", "Quartz"]'),
('Q148', 'How many bones are in the human body?', '206', 'Buzzer', 'medium', '["186", "226", "246"]'),
('Q149', 'What is the capital of Australia?', 'Canberra', 'Buzzer', 'medium', '["Sydney", "Melbourne", "Perth"]'),
('Q150', 'Which gas makes up most of the Earth''s atmosphere?', 'Nitrogen', 'Buzzer', 'medium', '["Oxygen", "Carbon Dioxide", "Argon"]'),
('Q151', 'What is the speed of light?', '299,792,458 meters per second', 'Buzzer', 'medium', '["186,282 miles per second", "300,000 km/s", "299,792,458 km/s"]'),
('Q152', 'Who discovered penicillin?', 'Alexander Fleming', 'Buzzer', 'medium', '["Louis Pasteur", "Marie Curie", "Jonas Salk"]'),
('Q153', 'What is the largest desert in the world?', 'Antarctica', 'Buzzer', 'medium', '["Sahara", "Gobi", "Kalahari"]'),
('Q154', 'How many chambers does a human heart have?', '4', 'Buzzer', 'medium', '["2", "3", "6"]'),
('Q155', 'What is the currency of Japan?', 'Yen', 'Buzzer', 'medium', '["Won", "Yuan", "Ringgit"]'),
('Q156', 'Which element has the chemical symbol O?', 'Oxygen', 'Buzzer', 'medium', '["Osmium", "Oganesson", "Olivine"]'),
('Q157', 'What is the deepest ocean trench?', 'Mariana Trench', 'Buzzer', 'medium', '["Puerto Rico Trench", "Japan Trench", "Peru-Chile Trench"]'),
('Q158', 'Who invented the telephone?', 'Alexander Graham Bell', 'Buzzer', 'medium', '["Thomas Edison", "Nikola Tesla", "Benjamin Franklin"]'),
('Q159', 'What is the largest organ in the human body?', 'Skin', 'Buzzer', 'medium', '["Liver", "Lungs", "Brain"]'),
('Q160', 'Which country has the most natural lakes?', 'Canada', 'Buzzer', 'medium', '["Finland", "Russia", "Sweden"]'),
('Q161', 'What is the formula for water?', 'H2O', 'Buzzer', 'medium', '["H2O2", "HO2", "H3O"]'),
('Q162', 'Who was the first person to walk on the moon?', 'Neil Armstrong', 'Buzzer', 'medium', '["Buzz Aldrin", "John Glenn", "Alan Shepard"]'),
('Q163', 'What is the capital of Brazil?', 'Brasília', 'Buzzer', 'medium', '["Rio de Janeiro", "São Paulo", "Salvador"]'),
('Q164', 'Which blood type is known as the universal donor?', 'O negative', 'Buzzer', 'medium', '["AB positive", "O positive", "A negative"]'),
('Q165', 'What is the most abundant element in the universe?', 'Hydrogen', 'Buzzer', 'medium', '["Helium", "Oxygen", "Carbon"]'),
('Q166', 'Who composed The Four Seasons?', 'Antonio Vivaldi', 'Buzzer', 'medium', '["Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven"]'),
('Q167', 'What is the largest island in the world?', 'Greenland', 'Buzzer', 'medium', '["Australia", "Madagascar", "Borneo"]'),
('Q168', 'How many strings does a standard guitar have?', '6', 'Buzzer', 'medium', '["4", "8", "12"]'),
('Q169', 'What is the study of earthquakes called?', 'Seismology', 'Buzzer', 'medium', '["Geology", "Meteorology", "Volcanology"]'),
('Q170', 'Which vitamin is produced when skin is exposed to sunlight?', 'Vitamin D', 'Buzzer', 'medium', '["Vitamin C", "Vitamin A", "Vitamin K"]'),
('Q171', 'What is the smallest bone in the human body?', 'Stapes', 'Buzzer', 'hard', '["Malleus", "Incus", "Hyoid"]'),
('Q172', 'Who wrote "One Hundred Years of Solitude"?', 'Gabriel García Márquez', 'Buzzer', 'hard', '["Mario Vargas Llosa", "Jorge Luis Borges", "Octavio Paz"]'),
('Q173', 'What do you call a baby horse?', 'Foal', 'Buzzer', 'easy', '["Colt", "Pony", "Calf"]'),
('Q174', 'How many hours are in a day?', '24', 'Buzzer', 'easy', '["20", "25", "30"]'),
('Q175', 'What is the main ingredient in bread?', 'Flour', 'Buzzer', 'easy', '["Sugar", "Salt", "Water"]'),
('Q176', 'What do you call frozen rain?', 'Hail', 'Buzzer', 'easy', '["Snow", "Sleet", "Ice"]'),
('Q177', 'What is the opposite of up?', 'Down', 'Buzzer', 'easy', '["Left", "Right", "Back"]'),
('Q178', 'How many legs does an insect have?', '6', 'Buzzer', 'easy', '["4", "8", "10"]'),
('Q179', 'What is the color of grass?', 'Green', 'Buzzer', 'easy', '["Blue", "Yellow", "Red"]'),
('Q180', 'What do you use to cut paper?', 'Scissors', 'Buzzer', 'easy', '["Knife", "Ruler", "Pen"]'),
('Q181', 'What is the largest continent?', 'Asia', 'Buzzer', 'medium', '["Africa", "North America", "Europe"]'),
('Q182', 'Who invented the light bulb?', 'Thomas Edison', 'Buzzer', 'medium', '["Benjamin Franklin", "Nikola Tesla", "Alexander Bell"]'),
('Q183', 'What is the freezing point of water in Celsius?', '0', 'Buzzer', 'medium', '["32", "-10", "100"]'),
('Q184', 'Which ocean is the smallest?', 'Arctic Ocean', 'Buzzer', 'medium', '["Indian Ocean", "Atlantic Ocean", "Southern Ocean"]'),
('Q185', 'What is the capital of Canada?', 'Ottawa', 'Buzzer', 'medium', '["Toronto", "Montreal", "Vancouver"]'),
('Q186', 'How many sides does a hexagon have?', '6', 'Buzzer', 'medium', '["5", "7", "8"]'),
('Q187', 'What is the hardest rock?', 'Diamond', 'Buzzer', 'medium', '["Granite", "Marble", "Quartz"]'),
('Q188', 'Which planet is closest to the sun?', 'Mercury', 'Buzzer', 'medium', '["Venus", "Earth", "Mars"]'),
('Q189', 'What gas do plants absorb from the air?', 'Carbon Dioxide', 'Buzzer', 'medium', '["Oxygen", "Nitrogen", "Hydrogen"]'),
('Q190', 'How many minutes are in half an hour?', '30', 'Buzzer', 'easy', '["25", "35", "40"]'),
('Q191', 'What is the square root of 64?', '8', 'Buzzer', 'medium', '["6", "7", "9"]'),
('Q192', 'Which element has the symbol Fe?', 'Iron', 'Buzzer', 'hard', '["Gold", "Silver", "Lead"]'),
('Q193', 'What is the longest bone in the human body?', 'Femur', 'Buzzer', 'hard', '["Tibia", "Humerus", "Radius"]'),
('Q194', 'Who painted "The Starry Night"?', 'Vincent van Gogh', 'Buzzer', 'hard', '["Pablo Picasso", "Claude Monet", "Salvador Dalí"]'),
('Q195', 'What is the pH of pure water?', '7', 'Buzzer', 'hard', '["0", "14", "10"]'),
('Q196', 'Which scientist developed the theory of relativity?', 'Albert Einstein', 'Buzzer', 'hard', '["Isaac Newton", "Galileo Galilei", "Stephen Hawking"]'),
('Q197', 'What is the most spoken language in the world?', 'Mandarin Chinese', 'Buzzer', 'medium', '["English", "Spanish", "Hindi"]'),
('Q198', 'How many chambers does a bird''s heart have?', '4', 'Buzzer', 'hard', '["2", "3", "5"]'),
('Q199', 'What is the chemical formula for table salt?', 'NaCl', 'Buzzer', 'hard', '["KCl", "CaCl2", "MgCl2"]'),
('Q200', 'Which country invented pizza?', 'Italy', 'Buzzer', 'easy', '["Greece", "France", "Spain"]');